[v int] Move "fake-cluster-control 1" invocation to runtest.
* test/runtest.in: Invoke "fake-cluster-control 1" here.
* test/Makefile.am (check_DATA): Remove fake-cluster/postmaster.pid.
(fake-cluster/postmaster.pid): Delete target.

diff --git a/test/runtest.in b/test/runtest.in
--- a/test/runtest.in
+++ b/test/runtest.in
@@ -43,6 +43,10 @@ then
     exit 1
 fi
 
+if ! $srcdir/fake-cluster-control 1 ; then
+    echo 'runtest: Could not prepare cluster and test db.'
+    exit 1
+fi
 test x"$DEBUG" = x || set -x
 exec ${GUILE-@GUILE@} $dopt \
     -L '@abs_top_srcdir@/build-aux' \
