[v] Do a partial install under test/; point ‘%load-path’ there.
* test/Makefile.am (check_DATA): New var.
(fake-install, clean-local): New targets.
* test/runtest.in: Don't set and export env var ‘GUILE_LOAD_PATH’;
add check for "proper" GUILE_LIBSITE; bail if improper;
arrange for ‘@GUILE_LIBSITE@’ to expand to the one under
the ./fake-install; display it if env var ‘DEBUG’ set;
add ‘-L "@GUILE_LIBSITE@"’ in args to the guile invocation.

* Makefile.am (noinst_DATA): Delete var.
(.module-catalog): Delete target.
(CLEANFILES): Delete var.
* configure.ac (mkpimmc): Delete GUILE_TOOLS_PROG.
(GUILE_MODULE_CATALOG_PREP): Delete macro call.

diff --git a/test/runtest.in b/test/runtest.in
--- a/test/runtest.in
+++ b/test/runtest.in
@@ -5,15 +5,27 @@ ts="@abs_top_srcdir@"
 tscm=`cd "$ts/src" ; pwd`
 export tscm
 
-GUILE_LOAD_PATH=`echo "@abs_top_builddir@:$GUILE_LOAD_PATH" | sed 's/:$//'`
-export GUILE_LOAD_PATH
-
 PGDATABASE='guile_pg_test'
 export PGDATABASE
 
 test x"$DEBUG" = x || dopt=--debug
 
+if [ x"$GUILE_LIBSITE" = x ] ; then
+    if echo '@GUILE_LIBSITE@' | grep -F '${prefix}' >/dev/null 2>&1
+        then : ; else
+        echo 'ERROR: Cannot determine fake GUILE_LIBSITE value.'
+        echo 'Try to set it in the environment.'
+        exit 1
+    fi
+fi
+
+prefix=`pwd`/fake-install
+exec_prefix="@exec_prefix@"
+libdir="@libdir@"
+test x"$DEBUG" = x || echo GUILE_LIBSITE: @GUILE_LIBSITE@
+
 exec ${GUILE-@GUILE@} $dopt \
+    -L "@GUILE_LIBSITE@" \
     -l "$ts/test/testing.scm" \
     -s $1
 
